server:
  port: 1025

spring:
  application:
    name: vcloud-eureka-server
  security:
    user:
      name: root #定义账户
      password: root #定义密码



eureka:
  client:
    fetch-registry: false #为false意味着无需注册自身
    register-with-eureka: false #为false意味着自身仅作为服务器，不作为客户端
    serviceUrl:
      defaultZone: http://root:root@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

logging:
  level:
    root: info
